### ISSUE TITLE
api url 문제점

### ISSUE THREAD

**Issue by parkjihwanjay** [RyanKor/60DB#73]
복통 설문을 보내는 url : api/surveys/stomach/
설문을 받는 url : api/stomach/복통 ID

-> 서로 다른 패턴이라 프론트에서 구조화하기 힘듬
-> 백에서 url 패턴 수정 필요

**Comment by parkjihwanjay** [comment]
> 해당 이슈의 문제점은 설문조사 관련된 url을 전부 수정해달라는 걸 말하는건가?

아뇨. 설문 받는 api만 수정하면 될거 같아요.

**Comment by RyanKor** [comment]
> > 해당 이슈의 문제점은 설문조사 관련된 url을 전부 수정해달라는 걸 말하는건가?
> 
> 아뇨. 설문 받는 api만 수정하면 될거 같아요.

REST 포팻 맞춰서 패턴 통일해달라는 거지? 그럼 내가 개천절 날 작업할게

**Comment by antlikelion** [comment]
제가 수정했습니다~
