### ISSUE TITLE
프로필 이미지 관련 오류

### ISSUE THREAD

**Issue by parkjihwanjay** [RyanKor/60DB#76]
프로필 페이지에 들어갔을때(http://localhost:8080/profiles, http://localhost:8080/profileupdate) 
이미지 관련 오류 발생

<img width="436" alt="스크린샷 2019-09-29 오후 11 19 47" src="https://user-images.githubusercontent.com/48053238/65833849-c7f13880-e30f-11e9-93cd-caa903d7c828.png">

**Comment by antlikelion** [comment]
작업예정입니다

**Comment by parkjihwanjay** [comment]
이미지 업로드 말고 그냥 기본 이미지로 고정하면 좋을 것 같습니다.

**Comment by parkjihwanjay** [comment]
> 작업예정입니다

이미지 업로드 말고 그냥 기본 이미지로 고정하면 좋을 것 같습니다.

**Comment by antlikelion** [comment]
해결되었습니다
